/** Douay-Rheims book slugs shared with Biblestr (`/{slug}/{chapter}`). */
export type DouayBook = {
  slug: string;
  name: string;
  /** `T` tag value on kind-30041 / chapter indexes. */
  code: string;
  testament: 'OT' | 'NT';
  chapters: number;
  aliases: string[];
};

export const DOUAY_EDITION_D = 'bible-the-bible-douay-rheims-version';

export const DOUAY_BOOKS: DouayBook[] = [
	{
    slug: 'genesis',
    name: 'Genesis',
    code: 'genesis',
    testament: 'OT',
    chapters: 50,
    aliases: ['gen', 'gn'] },
	{
    slug: 'exodus',
    name: 'Exodus',
    code: 'exodus',
    testament: 'OT',
    chapters: 40,
    aliases: ['exod', 'ex'] },
	{
    slug: 'leviticus',
    name: 'Leviticus',
    code: 'leviticus',
    testament: 'OT',
    chapters: 27,
    aliases: ['lev'] },
	{
    slug: 'numbers',
    name: 'Numbers',
    code: 'numbers',
    testament: 'OT',
    chapters: 36,
    aliases: ['num', 'nm'] },
	{
    slug: 'deuteronomy',
    name: 'Deuteronomy',
    code: 'deuteronomy',
    testament: 'OT',
    chapters: 34,
    aliases: ['deut', 'dt'] },
	{
    slug: 'joshua',
    name: 'Josue',
    code: 'joshua',
    testament: 'OT',
    chapters: 24,
    aliases: ['josue', 'josh', 'jos'] },
	{
    slug: 'judges',
    name: 'Judges',
    code: 'judges',
    testament: 'OT',
    chapters: 21,
    aliases: ['judg', 'jgs'] },
	{
    slug: 'ruth',
    name: 'Ruth',
    code: 'ruth',
    testament: 'OT',
    chapters: 4,
    aliases: ['ru'] },
	{
    slug: '1-samuel',
    name: '1 Kings',
    code: '1-samuel',
    testament: 'OT',
    chapters: 31,
    aliases: ['1 samuel', '1samuel', '1 sam', '1sam', 'i samuel', '1 kings', '1kings', 'i kings', '1kg', '1 kg'] },
	{
    slug: '2-samuel',
    name: '2 Kings',
    code: '2-samuel',
    testament: 'OT',
    chapters: 24,
    aliases: ['2 samuel', '2samuel', '2 sam', '2sam', 'ii samuel', '2 kings', '2kings', 'ii kings', '2kg', '2 kg'] },
	{
    slug: '1-kings',
    name: '3 Kings',
    code: '1-kings',
    testament: 'OT',
    chapters: 22,
    aliases: ['3 kings', '3kings', 'iii kings', '1 kings protestant', '3kg', '3 kg'] },
	{
    slug: '2-kings',
    name: '4 Kings',
    code: '2-kings',
    testament: 'OT',
    chapters: 25,
    aliases: ['4 kings', '4kings', 'iv kings', '2 kings protestant', '4kg', '4 kg'] },
	{
    slug: '1-chronicles',
    name: '1 Paralipomenon',
    code: '1-chronicles',
    testament: 'OT',
    chapters: 29,
    aliases: ['1 paralipomenon', '1chronicles', '1 chr', '1chr', 'i chronicles', '1ch', '1 ch', '1par', '1 par'] },
	{
    slug: '2-chronicles',
    name: '2 Paralipomenon',
    code: '2-chronicles',
    testament: 'OT',
    chapters: 36,
    aliases: ['2 paralipomenon', '2chronicles', '2 chr', '2chr', 'ii chronicles', '2ch', '2 ch', '2par', '2 par'] },
	{
    slug: 'ezra',
    name: '1 Esdras',
    code: 'ezra',
    testament: 'OT',
    chapters: 10,
    aliases: ['1 esdras', 'esdras', 'ezr', '1 esd', '1esd'] },
	{
    slug: 'nehemiah',
    name: '2 Esdras',
    code: 'nehemiah',
    testament: 'OT',
    chapters: 13,
    aliases: ['2 esdras', 'nehemias', 'neh', '2 esd', '2esd'] },
	{
    slug: 'tobit',
    name: 'Tobias',
    code: 'the-book-of-tobias',
    testament: 'OT',
    chapters: 14,
    aliases: ['tobias', 'tob'] },
	{
    slug: 'judith',
    name: 'Judith',
    code: 'judith',
    testament: 'OT',
    chapters: 16,
    aliases: ['jdt', 'jdth'] },
	{
    slug: 'esther',
    name: 'Esther',
    code: 'esther',
    testament: 'OT',
    chapters: 16,
    aliases: ['esth', 'est'] },
	{
    slug: 'job',
    name: 'Job',
    code: 'job',
    testament: 'OT',
    chapters: 42,
    aliases: ['jb'] },
	{
    slug: 'psalms',
    name: 'Psalms',
    code: 'psalms',
    testament: 'OT',
    chapters: 150,
    aliases: ['psalm', 'ps', 'psa'] },
	{
    slug: 'proverbs',
    name: 'Proverbs',
    code: 'proverbs',
    testament: 'OT',
    chapters: 31,
    aliases: ['prov', 'prv'] },
	{
    slug: 'ecclesiastes',
    name: 'Ecclesiastes',
    code: 'ecclesiastes',
    testament: 'OT',
    chapters: 12,
    aliases: ['eccl', 'ecc'] },
	{
    slug: 'song-of-solomon',
    name: 'Canticle of Canticles',
    code: 'song-of-solomon',
    testament: 'OT',
    chapters: 8,
    aliases: ['song of songs', 'song', 'canticles', 'canticle', 'cant'] },
	{
    slug: 'wisdom',
    name: 'Wisdom',
    code: 'wisdom',
    testament: 'OT',
    chapters: 19,
    aliases: ['wis'] },
	{
    slug: 'sirach',
    name: 'Ecclesiasticus',
    code: 'sirach',
    testament: 'OT',
    chapters: 51,
    aliases: ['ecclesiasticus', 'sir', 'ecclus'] },
	{
    slug: 'isaiah',
    name: 'Isaias',
    code: 'isaiah',
    testament: 'OT',
    chapters: 66,
    aliases: ['isaias', 'isa', 'is'] },
	{
    slug: 'jeremiah',
    name: 'Jeremias',
    code: 'jeremiah',
    testament: 'OT',
    chapters: 52,
    aliases: ['jeremias', 'jer'] },
	{
    slug: 'lamentations',
    name: 'Lamentations',
    code: 'lamentations',
    testament: 'OT',
    chapters: 5,
    aliases: ['lam'] },
	{
    slug: 'baruch',
    name: 'Baruch',
    code: 'baruch',
    testament: 'OT',
    chapters: 6,
    aliases: ['bar'] },
	{
    slug: 'ezekiel',
    name: 'Ezechiel',
    code: 'ezekiel',
    testament: 'OT',
    chapters: 48,
    aliases: ['ezechiel', 'ezek', 'ez', 'eze'] },
	{
    slug: 'daniel',
    name: 'Daniel',
    code: 'daniel',
    testament: 'OT',
    chapters: 14,
    aliases: ['dan', 'dn'] },
	{
    slug: 'hosea',
    name: 'Osee',
    code: 'hosea',
    testament: 'OT',
    chapters: 14,
    aliases: ['osee', 'hos'] },
	{
    slug: 'joel',
    name: 'Joel',
    code: 'joel',
    testament: 'OT',
    chapters: 3,
    aliases: ['jl'] },
	{
    slug: 'amos',
    name: 'Amos',
    code: 'amos',
    testament: 'OT',
    chapters: 9,
    aliases: ['am'] },
	{
    slug: 'obadiah',
    name: 'Abdias',
    code: 'obadiah',
    testament: 'OT',
    chapters: 1,
    aliases: ['abdias', 'obad'] },
	{
    slug: 'jonah',
    name: 'Jonas',
    code: 'jonah',
    testament: 'OT',
    chapters: 4,
    aliases: ['jonas', 'jon'] },
	{
    slug: 'micah',
    name: 'Micheas',
    code: 'micah',
    testament: 'OT',
    chapters: 7,
    aliases: ['micheas', 'mic'] },
	{
    slug: 'nahum',
    name: 'Nahum',
    code: 'nahum',
    testament: 'OT',
    chapters: 3,
    aliases: ['nah'] },
	{
    slug: 'habakkuk',
    name: 'Habacuc',
    code: 'habakkuk',
    testament: 'OT',
    chapters: 3,
    aliases: ['habacuc', 'hab'] },
	{
    slug: 'zephaniah',
    name: 'Sophonias',
    code: 'zephaniah',
    testament: 'OT',
    chapters: 3,
    aliases: ['sophonias', 'zeph', 'sophon'] },
	{
    slug: 'haggai',
    name: 'Aggeus',
    code: 'haggai',
    testament: 'OT',
    chapters: 2,
    aliases: ['aggeus', 'hag'] },
	{
    slug: 'zechariah',
    name: 'Zacharias',
    code: 'zechariah',
    testament: 'OT',
    chapters: 14,
    aliases: ['zacharias', 'zech', 'zac'] },
	{
    slug: 'malachi',
    name: 'Malachias',
    code: 'malachi',
    testament: 'OT',
    chapters: 4,
    aliases: ['malachias', 'mal'] },
	{
    slug: '1-maccabees',
    name: '1 Machabees',
    code: '1-maccabees',
    testament: 'OT',
    chapters: 16,
    aliases: ['1 machabees', '1maccabees', '1 macc', 'i maccabees', '1 mc', '1mc', '1 mac'] },
	{
    slug: '2-maccabees',
    name: '2 Machabees',
    code: '2-maccabees',
    testament: 'OT',
    chapters: 15,
    aliases: ['2 machabees', '2maccabees', '2 macc', 'ii maccabees', '2 mc', '2mc', '2 mac'] },
	{
    slug: 'matthew',
    name: 'Matthew',
    code: 'matthew',
    testament: 'NT',
    chapters: 28,
    aliases: ['matt', 'mt'] },
	{
    slug: 'mark',
    name: 'Mark',
    code: 'mark',
    testament: 'NT',
    chapters: 16,
    aliases: ['mk'] },
	{
    slug: 'luke',
    name: 'Luke',
    code: 'luke',
    testament: 'NT',
    chapters: 24,
    aliases: ['lk'] },
	{
    slug: 'john',
    name: 'John',
    code: 'john',
    testament: 'NT',
    chapters: 21,
    aliases: ['jn'] },
	{
    slug: 'acts',
    name: 'Acts',
    code: 'acts',
    testament: 'NT',
    chapters: 28,
    aliases: ['acts of the apostles'] },
	{
    slug: 'romans',
    name: 'Romans',
    code: 'romans',
    testament: 'NT',
    chapters: 16,
    aliases: ['rom'] },
	{
    slug: '1-corinthians',
    name: '1 Corinthians',
    code: '1-corinthians',
    testament: 'NT',
    chapters: 16,
    aliases: ['1 corinthians', '1cor', '1 cor', 'i corinthians'] },
	{
    slug: '2-corinthians',
    name: '2 Corinthians',
    code: '2-corinthians',
    testament: 'NT',
    chapters: 13,
    aliases: ['2 corinthians', '2cor', '2 cor', 'ii corinthians'] },
	{
    slug: 'galatians',
    name: 'Galatians',
    code: 'galatians',
    testament: 'NT',
    chapters: 6,
    aliases: ['gal'] },
	{
    slug: 'ephesians',
    name: 'Ephesians',
    code: 'ephesians',
    testament: 'NT',
    chapters: 6,
    aliases: ['eph'] },
	{
    slug: 'philippians',
    name: 'Philippians',
    code: 'philippians',
    testament: 'NT',
    chapters: 4,
    aliases: ['phil'] },
	{
    slug: 'colossians',
    name: 'Colossians',
    code: 'colossians',
    testament: 'NT',
    chapters: 4,
    aliases: ['col'] },
	{
    slug: '1-thessalonians',
    name: '1 Thessalonians',
    code: '1-thessalonians',
    testament: 'NT',
    chapters: 5,
    aliases: ['1 thessalonians', '1thess', '1 thess', 'i thessalonians', '1thes', '1 thes'] },
	{
    slug: '2-thessalonians',
    name: '2 Thessalonians',
    code: '2-thessalonians',
    testament: 'NT',
    chapters: 3,
    aliases: ['2 thessalonians', '2thess', '2 thess', 'ii thessalonians', '2thes', '2 thes'] },
	{
    slug: '1-timothy',
    name: '1 Timothy',
    code: '1-timothy',
    testament: 'NT',
    chapters: 6,
    aliases: ['1 timothy', '1tim', '1 tim', 'i timothy'] },
	{
    slug: '2-timothy',
    name: '2 Timothy',
    code: '2-timothy',
    testament: 'NT',
    chapters: 4,
    aliases: ['2 timothy', '2tim', '2 tim', 'ii timothy'] },
	{
    slug: 'titus',
    name: 'Titus',
    code: 'titus',
    testament: 'NT',
    chapters: 3,
    aliases: ['ti'] },
	{
    slug: 'philemon',
    name: 'Philemon',
    code: 'philemon',
    testament: 'NT',
    chapters: 1,
    aliases: ['phlm', 'phm'] },
	{
    slug: 'hebrews',
    name: 'Hebrews',
    code: 'hebrews',
    testament: 'NT',
    chapters: 13,
    aliases: ['heb'] },
	{
    slug: 'james',
    name: 'James',
    code: 'james',
    testament: 'NT',
    chapters: 5,
    aliases: ['jas'] },
	{
    slug: '1-peter',
    name: '1 Peter',
    code: '1-peter',
    testament: 'NT',
    chapters: 5,
    aliases: ['1 peter', '1pet', '1 pet', 'i peter'] },
	{
    slug: '2-peter',
    name: '2 Peter',
    code: '2-peter',
    testament: 'NT',
    chapters: 3,
    aliases: ['2 peter', '2pet', '2 pet', 'ii peter'] },
	{
    slug: '1-john',
    name: '1 John',
    code: '1-john',
    testament: 'NT',
    chapters: 5,
    aliases: ['1 john', '1jn', '1 jn', 'i john'] },
	{
    slug: '2-john',
    name: '2 John',
    code: '2-john',
    testament: 'NT',
    chapters: 1,
    aliases: ['2 john', '2jn', '2 jn', 'ii john'] },
	{
    slug: '3-john',
    name: '3 John',
    code: '3-john',
    testament: 'NT',
    chapters: 1,
    aliases: ['3 john', '3jn', '3 jn', 'iii john'] },
	{
    slug: 'jude',
    name: 'Jude',
    code: 'jude',
    testament: 'NT',
    chapters: 1,
    aliases: [] },
	{
    slug: 'revelation',
    name: 'Apocalypse',
    code: 'revelation',
    testament: 'NT',
    chapters: 22,
    aliases: ['apocalypse', 'rev', 'apoc'] }
];

const bySlug = new Map(DOUAY_BOOKS.map((b) => [b.slug, b]));
const byCode = new Map(DOUAY_BOOKS.map((b) => [b.code, b]));

export function douayBookBySlug(slug: string): DouayBook | null {
  return bySlug.get((slug || '').trim().toLowerCase()) ?? null;
}

export function douayBookByCode(code: string): DouayBook | null {
  return byCode.get((code || '').trim().toLowerCase()) ?? null;
}

export function isDouayBookSlug(slug: string): boolean {
  return douayBookBySlug(slug) != null;
}
